### ISSUE TITLE
is there any way to change pagination color dynamically

### ISSUE THREAD

**Issue by Sakthi002** [sant123/vuejs-uib-pagination#17]
![page](https://user-images.githubusercontent.com/35330401/51822725-2ee2cb80-2303-11e9-99c2-cfab650e670f.PNG)
![page1](https://user-images.githubusercontent.com/35330401/51822727-2ee2cb80-2303-11e9-99e1-bcbe5f46617c.PNG)

**Comment by Sakthi002** [comment]
any props

**Comment by sant123** [comment]
Hi @Sakthi002, currently this is not possible by design. Remember is a pagination Bootstrap based https://getbootstrap.com/docs/3.3/components/#pagination and the default active background is #337ab7. A workaround is wrap the pagination with any class you want, and modify Bootstrap class from there:

HTML
``` vue
<div class="make-me-green">
  <div is="uib-pagination" :total-items="totalItems" v-model="pagination1" @change="pageChanged()"></div>
</div>
```
CSS
``` css
.make-me-green .pagination .active a {
    background-color: #3c763d;
    border-color: #3c763d;
}
```

![image](https://user-images.githubusercontent.com/7959437/51856446-b9283100-22fd-11e9-99b1-8209264d4475.png)

Hope it helps :smile:

**Comment by Sakthi002** [comment]
thank you sir.
