### ISSUE TITLE
How to add button text as Prev and Next

### ISSUE THREAD

**Issue by shakirayoub123** [sant123/vuejs-uib-pagination#20]
how do i hide the page numbers between the prev and next button, i simply want to display two buttons prev and next

**Comment by shakirayoub123** [comment]
DONE

**Comment by sant123** [comment]
Hey 👋🏼 I see two situations here:

For changing the texts for `Prev` and `Next` do the following:

```vue
<div is="uib-pagination" v-model="pagination" previous-text="Prev" next-text="Next"></div>
```

For hiding the page numbers that's currently not supported and is out of the scope of this module. Since this was inspired by [pagination](https://angular-ui.github.io/bootstrap/#pagination) not [pager](https://angular-ui.github.io/bootstrap/#pager).

However there is a workaround that may work for you and is adding this style:

```css
.pagination-page {
  display: none !important;
}
```
