### ISSUE TITLE
[error] The build requres template compiler in project

### ISSUE THREAD

**Issue by stefan-angelov** [sant123/vuejs-uib-pagination#3]
When i try to use the plugin, Vue gives me this error: 

> You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

I use vue-cli webpack template with option:

> Runtime-only: about 6KB lighter min+gzip, but templates (or any Vue-specific HTML) are ONLY allowed in .vue files - render functions are required elsewhere

**Comment by sant123** [comment]
Hi @stefan-angelov, it seems you want to use single file components right? Please follow [this](https://github.com/vuejs-templates/webpack-simple/blob/master/template/webpack.config.js) configuration file por webpack when using it. You will see that it uses the full core of Vue.js using this:

```js
  resolve: {
    alias: {
      'vue$': 'vue/dist/vue.esm.js'
    }
  }
```
The reason is simple, this plugin uses a template to render the html into the component; that is why only runtime build is useless for this.
